import { cubicBezier } from "shoji_wm";

export const theme = {
  metrics: {
    innerGap: 8,
    outerGap: 10,
    singleWindowGap: 2,
    tiledRadius: 6,
    floatingRadius: 11,
    borderWidth: 2,
    titlebarHeight: 30,
    splitResizeStep: 100,
  },
  animation: {
    openDuration: 160,
    closeDuration: 120,
    layoutDuration: 160,
    windowManagementDuration: 170,
    focusDuration: 100,
    workspaceDuration: 200,
    openOffsetY: 12,
    closeOffsetY: 8,
    minimizeOffsetY: 24,
    windowEasing: cubicBezier(0.16, 1, 0.3, 1),
    workspaceEasing: cubicBezier(0.65, 0, 0.35, 1),
  },
  colors: {
    transparent: "#00000000",
    windowBackground: "#10131900",
    focusedBorder: { red: 215, green: 186, blue: 125, alpha: 1 },
    unfocusedBorder: { red: 79, green: 86, blue: 102, alpha: 0.72 },
    focusedTitlebar: { red: 31, green: 36, blue: 48, alpha: 0.5 },
    unfocusedTitlebar: { red: 42, green: 47, blue: 58, alpha: 0.5 },
    focusedTitle: "#f5f7fa",
    unfocusedTitle: "#c9d1d9",
    controlBackground: "#FFFFFF20",
    closeControlBorder: "#F0808030",
    maximizeControlBorder: "#00BFFF30",
    minimizeControlBorder: "#F8FF7530",
  },
  effects: {
    blurRadius: 4,
    blurPasses: 2,
    capturePadding: 24,
    damagePadding: 8,
    popupCapturePadding: 72,
    maskOpacityThreshold: 0.25,
    maskFeather: 0.04,
    glassRadius: 10,
    glassDistortionDepth: 0.2,
    glassDistortionStrength: 0.15,
    glassChromaticShift: 3,
    glassTint: 0.9,
  },
} as const;
