import { cubicBezier } from "shoji_wm";

export const theme = {
  dropIndicator: {
    opacity: 0.22,
    borderOpacity: 0.72,
    radius: 8,
    inset: 6,
    duration: 100,
  },
  metrics: {
    innerGap: 8,
    outerGap: 10,
    singleWindowGap: 2,
    tiledRadius: 6,
    floatingRadius: 11,
    borderWidth: 1,
    titlebarHeight: 30,
    splitResizeStep: 100,
  },
  animation: {
    openDuration: 160,
    closeDuration: 120,
    layoutDuration: 160,
    windowManagementDuration: 170,
    focusDuration: 100,
    workspaceDuration: 200,
    openOffsetY: 12,
    closeOffsetY: 8,
    minimizeOffsetY: 24,
    windowEasing: cubicBezier(0.16, 1, 0.3, 1),
    workspaceEasing: cubicBezier(0.65, 0, 0.35, 1),
  },
  colors: {
    transparent: "#00000000",
    windowBackground: "#11151B24",
    focusedBorder: "#71839A80",
    unfocusedBorder: "#343E4A70",
    focusedTitlebar: "#171C24E6",
    unfocusedTitlebar: "#131820D9",
    focusedTitle: "#E6EAF0",
    unfocusedTitle: "#9AA5B4",
    controlBackground: "#FFFFFF14",
    closeControlBorder: "#F0808030",
    maximizeControlBorder: "#00BFFF30",
    minimizeControlBorder: "#F8FF7530",
    closeControlIcon: "#fec3c3",
    maximizeControlIcon: "#c3effe",
    minimizeControlIcon: "#f7fec3",
  },
  effects: {
    windowOpacity: 0.98,
    blurRadius: 4,
    blurPasses: 2,
    capturePadding: 24,
    damagePadding: 8,
    popupCapturePadding: 72,
    maskOpacityThreshold: 0.25,
    maskFeather: 0.04,
    glassRadius: 10,
    glassDistortionDepth: 0.2,
    glassDistortionStrength: 0.15,
    glassChromaticShift: 3,
    glassTint: 0.9,
  },
} as const;
