-- GENERATED by matugen. Run ~/.local/bin/apply-theme.sh.
colors = {
    accent = "rgba(94CDF7FF)",
    accentAlt = "rgba(CEC0E8FF)",
    inactiveBord = "rgba(8B9198FF)",
    background = "rgba(101417FF)",
    foreground = "rgba(DFE3E8FF)",
    error = "rgba(FFB4ABFF)",
    surface = "rgba(41474DFF)",
    groupLocked = "rgba(313539FF)",
}
