# ============================================================
#  Monitors — managed with nwg-displays (GUI). Run: nwg-displays
#  nwg-displays saves its changes directly into this file.
# ============================================================
monitor = DP-1, 2560x1440@180, 0x0, 1
monitor = DP-2, 2560x1440@180, 2560x0, 1