-- GENERATED by matugen. Run ~/.local/bin/apply-theme.sh.
colors = {
    accent = "rgba({{colors.primary.default.hex_alpha_stripped}})",
    accentAlt = "rgba({{colors.tertiary.default.hex_alpha_stripped}})",
    inactiveBord = "rgba({{colors.outline.default.hex_alpha_stripped}})",
    background = "rgba({{colors.surface.default.hex_alpha_stripped}})",
    foreground = "rgba({{colors.on_surface.default.hex_alpha_stripped}})",
    error = "rgba({{colors.error.default.hex_alpha_stripped}})",
    surface = "rgba({{colors.surface_variant.default.hex_alpha_stripped}})",
    groupLocked = "rgba({{colors.surface_container_highest.default.hex_alpha_stripped}})",
}
